#!/usr/bin/env bash
# Plays the Miku lock chime whenever the logind session transitions to Locked.
set -u
dbus-monitor --session \
  "type='signal',interface='org.freedesktop.login1.Session',member='Lock'" |
  while read -r line; do
    case "$line" in
      *"member=Lock"*) pw-play /home/luca/.local/share/sounds/miku-lock.wav ;;
    esac
  done